services:
  - type: web
    name: shruti-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      API_ID: 
        value: 31644092
      API_HASH: 
        value: e262cde552b427ce10d7db518d8676b6
      API_KEY:
        sync: false
      BOT_TOKEN: 8762877918:AAH_V8OvfY_IddZNBs8iXhuwQj1LyRkBISk
        sync: false
      MONGO_DB_URI: 
        value: mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION
      OWNER_ID:
        value: 7065040481
      OWNER_USERNAME:
        value: MAHU_MOD1
      BOT_USERNAME:
        value: TEAMH4XMUSICBOT
      UPSTREAM_REPO:
        value: https://github.com/NoxxOP/ShrutiMusic
      STRING_SESSION:
        sync: false
      GIT_TOKEN:
        sync: false
      HEROKU_API_KEY:
        sync: false
      HEROKU_APP_NAME:
        sync: false
      LOG_GROUP_ID:
        value: -1003627840628
      SUPPORT_GROUP:
        value: https://t.me/Mahulikes2
      SUPPORT_CHANNEL:
        value: https://t.me/+ih__WyXxtNQ3NTNl
      INSTAGRAM:
        value: https://instagram.com/yaduwanshi_nand
      YOUTUBE:
        value: https://youtube.com/@NandEditz
      GITHUB:
        value: https://github.com/NoxxOP
      DONATE:
        value: https://t.me/ShrutiBots/91
      START_IMG_URL: https://files.catbox.moe/p2na5j.jpg
        sync: false
